-- Execute este script no SQL Editor do Supabase para adicionar as novas colunas
ALTER TABLE checklists 
ADD COLUMN IF NOT EXISTS macaco BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS estepe BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS chave_roda BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS triangulo BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS radio BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS antena BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS sem_parar BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS tapetes BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS calotas BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS extintor BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS cartao_ticket_car BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS ar_condicionado BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS crlv BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS bateria BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS trava BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS manual BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS giroflex BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS pneus_dianteiros TEXT DEFAULT 'Bom',
ADD COLUMN IF NOT EXISTS pneus_traseiros TEXT DEFAULT 'Bom',
ADD COLUMN IF NOT EXISTS pneu_estepe TEXT DEFAULT 'Bom',
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'Saída',
ADD COLUMN IF NOT EXISTS current_km NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS km_photo TEXT;

-- Adicional: coluna para rastrear quem mandou para manutenção
ALTER TABLE maintenance_records
ADD COLUMN IF NOT EXISTS requester_name TEXT;
